apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
      - name: geth
        image: docker.io/ethereum/client-go:v1.10.25
        imagePullPolicy: Always
        ports:
        - containerPort: 8545
        - containerPort: 30303
        volumeMounts:
        - name: volume
          mountPath: /data
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  labels:
    # insert any desired labels to identify your claim
    app: test
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 2Gi
