apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
      - name: geth
        image: docker.io/ethereum/client-go:v1.10.25
        args:
        - "--http"
        - "--http.addr"
        - "0.0.0.0"
        - "--http.corsdomain"
        - "'*'"
        - "--http.port"
        - "8545"
        - "--http.vhosts"
        - "'*'"
        - "--http.api"
        - "'admin,personal,eth,net,web3,txpool,miner,clique,debug'"
        - "--password"
        - "/data/password"
        - "--allow-insecure-unlock"
        - "--nodiscover"
        - "--verbosity"
        - "4"
        - "--miner.gastarget"
        - "804247552"
        - "--miner.gasprice"
        - "0"
        - "--mine"
        - "--datadir"
        - "/data"
        - "--networkid"
        - "1999"
        - "--miner.etherbase"
        - "0x00000000000000000000000000000000000000af"
        imagePullPolicy: Always
        ports:
        - containerPort: 8545
        - containerPort: 30303
        volumeMounts:
        - name: volume
          mountPath: /data
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: geth
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth
  labels:
    # insert any desired labels to identify your claim
    app: geth
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: geth
spec:
  ports:
  - name: port-1
    port: 8545
    protocol: TCP
    targetPort: 8545
  - name: port-2
    port: 30303
    protocol: TCP
    targetPort: 30303
  selector:
    app: geth
  sessionAffinity: None
  type: ClusterIP
